In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dell\desktop\data science\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\dell\desktop\data science\.venv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\desktop\data science\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\desktop\data science\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\desktop\data science\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\desktop\data science\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\dell\desktop\data science\.venv\lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
import json
import pandas as pd
import psycopg2

In [4]:
pip install --upgrade psycopg2

Requirement already satisfied: psycopg2 in c:\users\dell\desktop\data science\.venv\lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#aggre_insurance

path1 = "C:/Users/Dell/Desktop/Data science/pulse/data/aggregated/insurance/country/india/state/"
agg_insur_list = os.listdir(path1)

columns1 ={"states":[],"years":[],"quater":[],"Transaction_type":[],"Transaction_count":[],"Transaction_amount":[]}

for state in agg_insur_list:
    current_states = path1 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            A =json.load(data)

            for i in A["data"]['transactionData']:
                name = i['name']
                count= i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amount)
                columns1["states"].append(state)
                columns1["years"].append(year)
                columns1["quater"].append(int(file.strip(".json")))


aggre_insurance = pd.DataFrame(columns1)
aggre_insurance["states"] = aggre_insurance["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggre_insurance["states"] = aggre_insurance["states"].str.replace("-"," ")
aggre_insurance["states"] = aggre_insurance["states"].str.title()
aggre_insurance["states"] = aggre_insurance["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
aggre_insurance

In [ ]:
#aggree transaction

path2 = "C:/Users/Dell/Desktop/Data science/pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list = os.listdir(path2)

columns2 ={"states":[],"years":[],"quater":[],"Transaction_type":[],"Transaction_count":[],"Transaction_amount":[]}

for state in agg_trans_list:
    current_states = path2 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            B =json.load(data)

            for i in B["data"]['transactionData']:
                name = i['name']
                count= i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["states"].append(state)
                columns2["years"].append(year)
                columns2["quater"].append(int(file.strip(".json")))


agg_transaction = pd.DataFrame(columns2)
agg_transaction["states"] = agg_transaction["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
agg_transaction["states"] = agg_transaction["states"].str.replace("-"," ")
agg_transaction["states"] = agg_transaction["states"].str.title()
agg_transaction["states"] = agg_transaction["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
agg_transaction

,states,years,quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,West Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West Bengal,2024,4,Others,421806,5.053641e+08

In [ ]:
#aggre_user

path3 = "C:/Users/Dell/Desktop/Data science/pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(path3)

columns3 ={"states":[],"years":[],"quater":[],"Brands":[],"Transaction_count":[],"Percentage":[]}

for state in agg_user_list:
    current_states = path3 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            C =json.load(data)

            try:

                for i in C["data"]["usersByDevice"]:
                    brand = i['brand']
                    count= i["count"]
                    percentage = i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["states"].append(state)
                    columns3["years"].append(year)
                    columns3["quater"].append(int(file.strip(".json")))

            except:
                pass
aggre_user = pd.DataFrame(columns3)
aggre_user["states"] = aggre_user["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggre_user["states"] = aggre_user["states"].str.replace("-"," ")
aggre_user["states"] = aggre_user["states"].str.title()
aggre_user["states"] = aggre_user["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
aggre_user

                 states years  quater   Brands  Transaction_count  Percentage
0     Andaman & Nicobar  2018       1   Xiaomi               1665    0.247033
1     Andaman & Nicobar  2018       1  Samsung               1445    0.214392
2     Andaman & Nicobar  2018       1     Vivo                982    0.145697
3     Andaman & Nicobar  2018       1     Oppo                501    0.074332
4     Andaman & Nicobar  2018       1  OnePlus                332    0.049258
...                 ...   ...     ...      ...                ...         ...
6727        West Bengal  2022       1   Lenovo             330017    0.015056
6728        West Bengal  2022       1  Infinix             284678    0.012987
6729        West Bengal  2022       1     Asus             280347    0.012790
6730        West Bengal  2022       1    Apple             277752    0.012671
6731        West Bengal  2022       1   Others            2196334    0.100199

[6732 rows x 6 columns]

In [ ]:
#map_insurance

path4 = "C:/Users/Dell/Desktop/Data science/pulse/data/map/insurance/hover/country/india/state/"
map_insur_list = os.listdir(path4)

columns4 ={"states":[],"years":[],"quater":[],"Districts":[],"Transaction_count":[],"Transaction_amount":[]}

for state in map_insur_list:
    current_states = path4 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            D =json.load(data)
            
            for i in D["data"]["hoverDataList"]:
                    name = i['name']
                    count= i["metric"][0]["count"]
                    amount = i["metric"][0]["amount"]
                    columns4["Districts"].append(name)
                    columns4["Transaction_count"].append(count)
                    columns4["Transaction_amount"].append(amount)
                    columns4["states"].append(state)
                    columns4["years"].append(year)
                    columns4["quater"].append(int(file.strip(".json")))

map_insurance = pd.DataFrame(columns4)
map_insurance["states"] = map_insurance["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_insurance["states"] = map_insurance["states"].str.replace("-"," ")
map_insurance["states"] = map_insurance["states"].str.title()
map_insurance["states"] = map_insurance["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
map_insurance

,states,years,quater,Districts,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [ ]:
#map transaction

path5 = "C:/Users/Dell/Desktop/Data science/pulse/data/map/transaction/hover/country/india/state/"
map_trans_list = os.listdir(path5)

columns5 ={"states":[],"years":[],"quater":[],"Districts":[],"Transaction_count":[],"Transaction_amount":[]}

for state in map_trans_list:
    current_states = path5 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            E =json.load(data)
            
            for i in E["data"]["hoverDataList"]:
                    name = i['name']
                    count= i["metric"][0]["count"]
                    amount = i["metric"][0]["amount"]
                    columns5["Districts"].append(name)
                    columns5["Transaction_count"].append(count)
                    columns5["Transaction_amount"].append(amount)
                    columns5["states"].append(state)
                    columns5["years"].append(year)
                    columns5["quater"].append(int(file.strip(".json")))

map_tran = pd.DataFrame(columns5)
map_tran["states"] =map_tran["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_tran["states"] =map_tran["states"].str.replace("-"," ")
map_tran["states"] =map_tran["states"].str.title()
map_tran["states"] = map_tran["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
map_tran

,states,years,quater,Districts,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06
3,Andaman & Nicobar,2018,2,north and middle andaman district,825,1.317863e+06
4,Andaman & Nicobar,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,West Bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,West Bengal,2024,4,nadia district,65274337,1.079320e+11
20602,West Bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,West Bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [ ]:
#map_user

path6 = "C:/Users/Dell/Desktop/Data science/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)

columns6 ={"states":[],"years":[],"quater":[],"Districts":[],"RegisteredUsers":[],"AppOpens":[]}

for state in map_user_list:
    current_states = path6 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            F =json.load(data)
            
            for i in F["data"]["hoverData"].items():
                            
                district = i[0]
                registeredUsers= i[1]["registeredUsers"]
                appOpens = i[1]["appOpens"]
                columns6["Districts"].append(district)
                columns6["RegisteredUsers"].append(registeredUsers)
                columns6["AppOpens"].append(appOpens)
                columns6["states"].append(state)
                columns6["years"].append(year)
                columns6["quater"].append(int(file.strip(".json")))


map_user = pd.DataFrame(columns6)
map_user["states"] =map_user["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_user["states"] =map_user["states"].str.replace("-"," ")
map_user["states"] =map_user["states"].str.title()
map_user["states"] = map_user["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
map_user

,states,years,quater,Districts,RegisteredUsers,AppOpens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [ ]:
#Top insurance

path7 = "C:/Users/Dell/Desktop/Data science/pulse/data/top/insurance/country/india/state/"
top_insur_list = os.listdir(path7)

columns7 ={"states":[],"years":[],"quater":[],"Pincodes":[],"Transaction_count":[],"Transaction_amount":[]}

for state in top_insur_list:
    current_states = path7 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            G =json.load(data)

            for i in G["data"]["pincodes"]:
                entityname = i["entityName"]         
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityname)   
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["states"].append(state)
                columns7["years"].append(year)
                columns7["quater"].append(int(file.strip(".json")))


top_insurance = pd.DataFrame(columns7)
top_insurance["states"] =top_insurance["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_insurance["states"] =top_insurance["states"].str.replace("-"," ")
top_insurance["states"] =top_insurance["states"].str.title()
top_insurance["states"] = top_insurance["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
top_insurance

,states,years,quater,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,744301,3,565.0
1,Andaman & Nicobar,2020,2,744104,2,513.0
2,Andaman & Nicobar,2020,2,744101,1,282.0
3,Andaman & Nicobar,2020,3,744112,9,3432.0
4,Andaman & Nicobar,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West Bengal,2024,4,711101,713,750354.0
6664,West Bengal,2024,4,700091,642,969634.0
6665,West Bengal,2024,4,700150,627,761501.0
6666,West Bengal,2024,4,700039,619,787836.0
6667,West Bengal,2024,4,700156,574,888613.0

In [ ]:
#top transaction

path8 = "C:/Users/Dell/Desktop/Data science/pulse/data/top/transaction/country/india/state/"
top_tans_list = os.listdir(path8)

columns8 ={"states":[],"years":[],"quater":[],"Pincodes":[],"Transaction_count":[],"Transaction_amount":[]}

for state in top_tans_list:
    current_states = path8 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            H =json.load(data)

            for i in H["data"]["pincodes"]:
                entityname = i["entityName"]         
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns8["Pincodes"].append(entityname)   
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["states"].append(state)
                columns8["years"].append(year)
                columns8["quater"].append(int(file.strip(".json")))

top_transaction = pd.DataFrame(columns8)
top_transaction["states"] =top_transaction["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_transaction["states"] =top_transaction["states"].str.replace("-"," ")
top_transaction["states"] =top_transaction["states"].str.title()
top_transaction["states"] = top_transaction["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
top_transaction

,states,years,quater,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West Bengal,2024,4,711101,6753348,1.049483e+10
9995,West Bengal,2024,4,700059,6662715,8.009476e+09
9996,West Bengal,2024,4,700039,6575693,9.018748e+09
9997,West Bengal,2024,4,734001,6432082,8.996529e+09
9998,West Bengal,2024,4,733134,6313560,1.050259e+10

In [ ]:
#top user

path9 = "C:/Users/Dell/Desktop/Data science/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path9)

columns9 ={"states":[],"years":[],"quater":[],"Pincodes":[],"RegisteredUsers":[]}

for state in top_user_list:
    current_states = path9 + state +"/"
    agg_year_list = os.listdir(current_states)
    
    for year in agg_year_list:
        current_year = current_states + year +"/"
        agg_file_list = os.listdir(current_year)
        
        for file in agg_file_list:
            current_file = current_year + file
            data = open(current_file,"r")


            I =json.load(data)

            for i in I["data"]["pincodes"]:
                entityname = i["name"]         
                registeredusers = i["registeredUsers"]
                columns9["Pincodes"].append(entityname)   
                columns9["RegisteredUsers"].append(registeredusers)
                columns9["states"].append(state)
                columns9["years"].append(year)
                columns9["quater"].append(int(file.strip(".json")))


top_users = pd.DataFrame(columns9)
top_users["states"] =top_users["states"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_users["states"] =top_users["states"].str.replace("-"," ")
top_users["states"] =top_users["states"].str.title()
top_users["states"] = top_users["states"].str.replace('dadra-&-nagar-haveli-&-daman-&-diu','Dadra and Nagar Haveli and Daman and Diu')
top_users

                 states years  quater Pincodes  RegisteredUsers
0     Andaman & Nicobar  2018       1   744103             1608
1     Andaman & Nicobar  2018       1   744101             1108
2     Andaman & Nicobar  2018       1   744105             1075
3     Andaman & Nicobar  2018       1   744102             1006
4     Andaman & Nicobar  2018       1   744104              272
...                 ...   ...     ...      ...              ...
9995        West Bengal  2024       4   733134           169596
9996        West Bengal  2024       4   700059           169448
9997        West Bengal  2024       4   711302           146034
9998        West Bengal  2024       4   700150           142151
9999        West Bengal  2024       4   711106           142077

[10000 rows x 5 columns]

In [ ]:
# Table creation

#sql connection

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

#aggregated insurance table

create_query_1 = "CREATE TABLE if not exists aggregated_insurance(states varchar(255),years int,quater int,Transaction_type varchar(255),Transaction_count bigint,Transaction_amount bigint)"

cursor.execute(create_query_1)
mydb.commit()

inser_query_1= "INSERT INTO aggregated_insurance(states,years,quater,Transaction_type,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = aggre_insurance.values.tolist()
cursor.executemany(inser_query_1,data)
mydb.commit()

#aggregated_transaction_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_2 = "CREATE TABLE if not exists aggregated_transaction(states varchar(255),years int,quater int,Transaction_type varchar(255),Transaction_count bigint,Transaction_amount bigint)"

cursor.execute(create_query_2)
mydb.commit()

inser_query_2= "INSERT INTO aggregated_transaction(states,years,quater,Transaction_type,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = agg_transaction.values.tolist()
cursor.executemany(inser_query_2,data)
mydb.commit()

#aggregated_user_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_3 = "CREATE TABLE if not exists aggregated_user(states varchar(255),years int,quater int,Brands varchar(255),Transaction_count bigint,Percentage float)"

cursor.execute(create_query_3)
mydb.commit()

inser_query_3= "INSERT INTO aggregated_user(states,years,quater,Brands,Transaction_count,Percentage) values(%s,%s,%s,%s,%s,%s)"


data = aggre_user.values.tolist()
cursor.executemany(inser_query_3,data)
mydb.commit()

#map_insurance_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_4 = "CREATE TABLE if not exists map_insurance(states varchar(255),years int,quater int,Districts varchar(255),Transaction_count bigint,Transaction_amount bigint)"

cursor.execute(create_query_4)
mydb.commit()

inser_query_4= "INSERT INTO map_insurance(states,years,quater,Districts,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = map_insurance.values.tolist()
cursor.executemany(inser_query_4,data)
mydb.commit()

#map_transaction_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_5 = "CREATE TABLE if not exists map_transaction(states varchar(255),years int,quater int,Districts varchar(255),Transaction_count bigint,Transaction_amount bigint)"

cursor.execute(create_query_5)
mydb.commit()

inser_query_5= "INSERT INTO map_transaction(states,years,quater,Districts,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = map_tran.values.tolist()
cursor.executemany(inser_query_5,data)
mydb.commit()

#map_user_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_6 = "CREATE TABLE if not exists map_user(states varchar(255),years int,quater int,Districts varchar(255),RegisteredUsers bigint,AppOpens bigint)"

cursor.execute(create_query_6)
mydb.commit()

inser_query_6= "INSERT INTO map_user(states,years,quater,Districts,RegisteredUsers,AppOpens) values(%s,%s,%s,%s,%s,%s)"


data = map_user.values.tolist()
cursor.executemany(inser_query_6,data)
mydb.commit()

#top_insurance_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_7 = "CREATE TABLE if not exists top_insurance(states varchar(255),years int(10),quater varchar(10),Pincodes varchar(10),Transaction_count VARCHAR(50),Transaction_amount VARCHAR(50))"

cursor.execute(create_query_7)
mydb.commit()

inser_query_7= "INSERT INTO top_insurance(states,years,quater,Pincodes,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = top_insurance.values.tolist()
cursor.executemany(inser_query_7,data)
mydb.commit()


#top_transaction_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_8 = "CREATE TABLE if not exists top_transaction(states varchar(255),years int(10),quater varchar(10),Pincodes varchar(10),Transaction_count VARCHAR(50),Transaction_amount VARCHAR(50))"

cursor.execute(create_query_8)
mydb.commit()

inser_query_8= "INSERT INTO top_transaction(states,years,quater,Pincodes,Transaction_count,Transaction_amount) values(%s,%s,%s,%s,%s,%s)"


data = top_transaction.values.tolist()
cursor.executemany(inser_query_8,data)
mydb.commit()

#top_user_table

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        port = "5432",
                        database = "phonepe_db",
                        password = "Swag5566!")

cursor= mydb.cursor()

create_query_9 = "CREATE TABLE if not exists top_users(states varchar(255),years int,quater int,Pincodes int,RegisteredUsers bigint)"

cursor.execute(create_query_9)
mydb.commit()

inser_query_9= "INSERT INTO top_users(states,years,quater,Pincodes,RegisteredUsers) values(%s,%s,%s,%s,%s)"


data = top_users.values.tolist()
cursor.executemany(inser_query_9,data)
mydb.commit()